baseURL = '/'
languageCode = 'en-us'
title = 'My New Hugo Site'   # will show in the Browser Tab
theme = 'hugo-sewing'
DefaultContentLanguage = "en"   # Theme's display language, supports: en, zh
footnotereturnlinkcontents = "↩"
pygmentsuseclasses = true 
staticDir = ["static"]
#enableGitInfo = true
disableKinds = ["GitInfo"]

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Feature"
    url = "/feature/"
    weight = 2
[[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 3
[[menu.main]]
    name = "Project"
    url = "/project/"
    weight = 4
[[menu.main]]
    name = "Publication"
    url = "/publication/"
    weight = 5
[[menu.main]]
    name = "People"
    url = "/people/"
    weight = 6
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 7
[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 8

[markup.goldmark.renderer]
unsafe= true

[frontmatter]
lastmod = ["lastmod", ":git", "date", "publishDate"]

[params]
    authorName = "Author Name"   # will show in the copyright
    enableTheme = true   # whether to display Theme information
    enableVisitor = false   # whether to display visitor information
    enableUpdated = false   # whether to display updating date information
    enableGiscus = true   # whether to display comment in blog and contact
    enableimgloop = true
    toc = true   # whether to display table of contents in blog

    [permalinks]
        blog = "/blog/:year/:month/:slug/"

    [params.Theme]
        url = "https://github.com/HaiyanKong/hugo-sewing"
        name = "Hugo-Sewing"

    [params.visitor]
        src = ""

    [params.memo]
        memos = ""
        limit = " "
        creatorId = " "
        domId = " "
        twiEnv = ""

    [params.giscus]  # see https://giscus.app/
        data_repo=""
        data_repo_id=""
        data_category="Announcements"
        data_category_id=""
        data_mapping="pathname"
        data_strict="0"
        data_reactions_enabled="1"
        data_emit_metadata="0"
        data_input_position="top"
        data_theme="light_tritanopia"
        data_lang="en"
        crossorigin="anonymous"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      linkify = false